### ISSUE TITLE
Task 2: `is_threatened`

### ISSUE THREAD

**Issue by bpowers24** [bpowers24/Demo-Repo#10]
# Task 2: Write a script to QAQC the data
## Team B: write code to add `is_threatened` column
- [x] Pull/fetch recent changes in GitHub desktop. 
- [x] After the `is_overweight` branch has been merged, create a new branch called `qaqc_for_threatened`.
- [x] On the new branch, open the `Demo-Repo.Rproj` file. 
- [x] Open `QAQC_zoo_animals.R`.
- [x] Starting at the top of the script, run each line of code until you get to the `4. Create is_threatened` chunk. 
- [x] "Write" code to add a column called `is_threatened`. There is a previous commit that has the code you need. Locate the commit history and find the commit "answers for 12/17 workshop here!". Copy and paste the code from an older version of `QAQC_zoo_animals.R`.
- [x] Run the line of code you added to create `zoo_animals_processed`. Then run the `test_that()` line below it to verify your work. Do not run any more code. 
- [x] When finished save your work, commit and push your changes. 
- [x] Return to GitHub web browser and submit a Pull Request, but DO NOT merge it.  

## Team A: review `is_threatened` PR
- [x] Open the pull request in GitHub web browser.
- [x] Look through the changes they proposed. 
- [x] If you agree with them, accept their pull request. 
- [x] Delete the branch. Notify Team B and have them delete the branch on their local machines. On GitHub desktop, fetch once (do not click "publish"). Delete the branch. Then fetch again. 

## Related Resources
https://github.com/bpowers24/Demo-Repo/blob/main/GitHub_Resources.md
