### ISSUE TITLE
Task 3: Plot results and answer our objectives

### ISSUE THREAD

**Issue by bpowers24** [bpowers24/Demo-Repo#11]
# Task 3: Plot results and answer our objectives

1. Which zoos have a threatened species? 
2. Of the threatened species, how many of those individuals are outside of their normal weight? 

Everyone should complete the following: 
- [ ] Pull/fetch recent changes in GitHub desktop. 
- [ ] On the main branch, open the `Demo-Repo.Rproj` file. 
- [ ] Open `QAQC_zoo_animals.R`.
- [ ] Run the entire script. 
- [ ] Use the plots to answer the questions. 
- [ ] Return to this GitHub issue and post your answers as a comment. 

## Check the box when you're done :)
- [x] Jake
- [x] VGC
- [x] Sophia
- [x] Lupita
- [x] Dillman
- [x] Maggi

**Comment by smckever** [comment]
1. All the zoos
2. 4 of the species

**Comment by mmlaan** [comment]
1. All
2. 4

**Comment by JakeCavaiani99** [comment]
1. All
2. 4

**Comment by vgc40** [comment]
1- All
2- 4

**Comment by LupitaRenteria** [comment]
1: All of them
2-4

**Comment by Dillman90** [comment]
1. All
2. 4
